version: '3'

services:
  react:
    container_name: sysken-react
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    ports:
      - 8081:8081
    tty:
      true