version: '3'

services:
  react:
    container_name: sysken-react
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/src
    ports:
      - 8080:8080
    expose:
      - 8080
    tty:
      true
